# Generated by Django 2.1 on 2018-08-27 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonationCommitmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=1000)),
                ('contact_number', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=1000)),
                ('district', models.CharField(max_length=1000)),
                ('pincode', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='DonationItemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
                ('crowd_sourced', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='donationitemmodel',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noah_core.ItemModel'),
        ),
        migrations.AddField(
            model_name='donationcommitmentmodel',
            name='items',
            field=models.ManyToManyField(to='noah_core.DonationItemModel'),
        ),
    ]
