# Generated by Django 2.1 on 2018-08-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noah_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
