# Generated by Django 2.1 on 2018-09-04 05:31

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('noah_core', '0002_auto_20180828_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationcommitmentmodel',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='donationcommitmentmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donationitemmodel',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='donationitemmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 9, 4, 5, 31, 11, 144717, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
