# Generated by Django 2.1.1 on 2018-09-19 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noah_core', '0003_auto_20180904_0531'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=250)),
                ('item_pic_url', models.CharField(blank=True, max_length=250, null=True)),
                ('donor_full_name', models.CharField(max_length=250)),
                ('donor_contact_number', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
                ('pincode', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HubModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('kind', models.IntegerField(choices=[(1, 'COLLECTION'), (2, 'DISTRIBUTION')])),
                ('address', models.TextField()),
                ('district', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
                ('pincode', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiverRequestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_full_name', models.CharField(max_length=250)),
                ('requester_number', models.CharField(max_length=10)),
                ('posting_for', models.IntegerField(choices=[(1, 'SELF'), (2, 'FAMILY'), (3, 'ORGANISATION')])),
                ('description', models.TextField()),
                ('damage_pic_url', models.CharField(blank=True, max_length=250, null=True)),
                ('item_name', models.CharField(max_length=25)),
                ('beneficiary_full_name', models.CharField(max_length=250)),
                ('beneficiary_number', models.CharField(max_length=10)),
                ('beneficiary_address', models.TextField()),
                ('beneficiary_district', models.CharField(max_length=250)),
                ('beneficiary_state', models.CharField(max_length=250)),
                ('beneficiary_pincode', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('kind', models.IntegerField()),
                ('current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TokenModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=250)),
                ('kind', models.IntegerField(choices=[(1, 'ACCESS'), (2, 'VERIFICATION')])),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('is_number_verified', models.BooleanField(default=False)),
                ('is_super', models.BooleanField(default=False)),
                ('is_access_controler', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerRequestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('number', models.CharField(max_length=10)),
                ('email_address', models.CharField(max_length=250)),
                ('district', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
                ('pincode', models.CharField(max_length=6)),
                ('contribution_type', models.IntegerField(choices=[(1, 'FULL_TIME'), (2, 'PART_TIME_WEEKDAYS'), (3, 'PART_TIME_WEEKDAYS_FULL_TIME_WEEKENDS'), (4, 'ONLY_WEEKENDS')])),
                ('vehicle_type', models.IntegerField(choices=[(1, 'CAR'), (2, 'BIKE'), (3, 'NO')])),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='noah_core.UserProfileModel')),
            ],
        ),
        migrations.AddField(
            model_name='tokenmodel',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noah_core.UserProfileModel'),
        ),
        migrations.AddField(
            model_name='statusmodel',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='noah_core.UserProfileModel'),
        ),
        migrations.AddField(
            model_name='receiverrequestmodel',
            name='statuses',
            field=models.ManyToManyField(to='noah_core.StatusModel'),
        ),
        migrations.AddField(
            model_name='hubmodel',
            name='admins',
            field=models.ManyToManyField(related_name='admins_set', to='noah_core.UserProfileModel'),
        ),
        migrations.AddField(
            model_name='hubmodel',
            name='volunteers',
            field=models.ManyToManyField(related_name='volunteers_set', to='noah_core.UserProfileModel'),
        ),
        migrations.AddField(
            model_name='donationmodel',
            name='collection_hub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_hub_set', to='noah_core.HubModel'),
        ),
        migrations.AddField(
            model_name='donationmodel',
            name='distribution_hub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribution_hub_set', to='noah_core.HubModel'),
        ),
        migrations.AddField(
            model_name='donationmodel',
            name='request_fulfilled',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='noah_core.ReceiverRequestModel'),
        ),
        migrations.AddField(
            model_name='donationmodel',
            name='statuses',
            field=models.ManyToManyField(to='noah_core.StatusModel'),
        ),
    ]
