# Generated by Django 2.1.1 on 2018-09-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noah_core', '0005_auto_20180919_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusmodel',
            name='group',
        ),
        migrations.AddField(
            model_name='volunteerrequestmodel',
            name='statuses',
            field=models.ManyToManyField(to='noah_core.StatusModel'),
        ),
    ]
