# Generated by Django 2.1.1 on 2018-09-19 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noah_core', '0006_auto_20180919_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofilemodel',
            old_name='is_access_controler',
            new_name='is_access_controller',
        ),
    ]
