const types = {
    CHOICES_SET_CONSTANT: "CHOICES_SET_CONSTANT",
    CHOICES_ADD_CUSTOM_ITEM: "CHOICES_ADD_CUSTOM_ITEM",
    CHOICES_SET_SELECTED_STATE: "CHOICES_SET_SELECTED_STATE"
}

export default types